// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package adaptors

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID              []byte
	UserID          []byte
	PublicKey       []byte
	AttestationType pgtype.Text
	Aaguid          []byte
	SignCount       int64
	Transports      []string
	Flags           int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Endpoint struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	Method     string
	Scope      string
	FunctionID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type Function struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	Name        string
	Language    string
	Path        string
	Description string
	CreatedBy   []byte
	CreatedAt   pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedBy   []byte
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID          []byte
	Name        string
	DisplayName string
	Icon        pgtype.Text
}

type UserProject struct {
	UserID    []byte
	ProjectID pgtype.UUID
	Role      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type UserSession struct {
	SessionID string
	UserID    []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UserAgent pgtype.Text
	IpAddress pgtype.Text
}

type WebauthnSession struct {
	SessionID          string
	UserName           string
	Challenge          []byte
	UserID             []byte
	AllowedCredentials [][]byte
	ExpiresAt          pgtype.Timestamptz
	RpID               pgtype.Text
	CredParams         []byte
	Extensions         []byte
	UserVerification   pgtype.Text
	Mediation          pgtype.Text
}
