// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package adaptors

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFunction = `-- name: CreateFunction :one
INSERT INTO functions (project_id, name, language, path, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, language, path, description, created_by, created_at
`

type CreateFunctionParams struct {
	ProjectID   pgtype.UUID
	Name        string
	Language    string
	Path        string
	Description string
	CreatedBy   []byte
}

func (q *Queries) CreateFunction(ctx context.Context, arg CreateFunctionParams) (Function, error) {
	row := q.db.QueryRow(ctx, createFunction,
		arg.ProjectID,
		arg.Name,
		arg.Language,
		arg.Path,
		arg.Description,
		arg.CreatedBy,
	)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Language,
		&i.Path,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFunction = `-- name: DeleteFunction :exec
DELETE FROM functions
WHERE id = $1
`

func (q *Queries) DeleteFunction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFunction, id)
	return err
}

const getFunctionByID = `-- name: GetFunctionByID :one
SELECT id, project_id, name, language, path, description, created_by, created_at
FROM functions
WHERE id = $1
`

func (q *Queries) GetFunctionByID(ctx context.Context, id pgtype.UUID) (Function, error) {
	row := q.db.QueryRow(ctx, getFunctionByID, id)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Language,
		&i.Path,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listFunctionsForProject = `-- name: ListFunctionsForProject :many
SELECT id, project_id, name, language, path, description, created_by, created_at
FROM functions
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFunctionsForProject(ctx context.Context, projectID pgtype.UUID) ([]Function, error) {
	rows, err := q.db.Query(ctx, listFunctionsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Function
	for rows.Next() {
		var i Function
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Language,
			&i.Path,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFunctionDescription = `-- name: UpdateFunctionDescription :one
UPDATE functions
SET description = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, language, path, description, created_by, created_at
`

type UpdateFunctionDescriptionParams struct {
	ID          pgtype.UUID
	Description string
}

func (q *Queries) UpdateFunctionDescription(ctx context.Context, arg UpdateFunctionDescriptionParams) (Function, error) {
	row := q.db.QueryRow(ctx, updateFunctionDescription, arg.ID, arg.Description)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Language,
		&i.Path,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateFunctionPath = `-- name: UpdateFunctionPath :one
UPDATE functions
SET path = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, language, path, description, created_by, created_at
`

type UpdateFunctionPathParams struct {
	ID   pgtype.UUID
	Path string
}

func (q *Queries) UpdateFunctionPath(ctx context.Context, arg UpdateFunctionPathParams) (Function, error) {
	row := q.db.QueryRow(ctx, updateFunctionPath, arg.ID, arg.Path)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Language,
		&i.Path,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
