// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package adaptors

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID              []byte
	UserID          []byte
	PublicKey       []byte
	AttestationType pgtype.Text
	Aaguid          []byte
	SignCount       int64
	Transports      []string
	Flags           int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type User struct {
	ID          []byte
	Name        string
	DisplayName string
	Icon        pgtype.Text
}

type UserSession struct {
	SessionID string
	UserID    []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UserAgent pgtype.Text
	IpAddress pgtype.Text
}

type WebauthnSession struct {
	SessionID          string
	UserName           string
	Challenge          []byte
	UserID             []byte
	AllowedCredentials [][]byte
	ExpiresAt          pgtype.Timestamptz
	RpID               pgtype.Text
	CredParams         []byte
	Extensions         []byte
	UserVerification   pgtype.Text
	Mediation          pgtype.Text
}
