// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func selectProject(id string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_selectProject_5fa6`,
		Function: `function __templ_selectProject_5fa6(id){document.cookie = "lws_project=" + id + "; path=/; SameSite=Lax"
	location.reload()
}`,
		Call:       templ.SafeScript(`__templ_selectProject_5fa6`, id),
		CallInline: templ.SafeScriptInline(`__templ_selectProject_5fa6`, id),
	}
}

func DashboardContent(username string, projects []Project, activeProjectID string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full px-6 md:px-14 py-12 space-y-14\"><!-- HEADER --><div class=\"flex items-center justify-between\"><h1 class=\"text-3xl md:text-4xl font-semibold text-white tracking-tight\">Dashboard</h1><div class=\"relative\"><button id=\"profile-btn\" class=\"flex items-center gap-3 px-3 py-2 bg-[#0e0e0f] border border-neutral-800 rounded-xl hover:border-neutral-600 transition\"><img src=\"/static/imgs/user.png\" class=\"w-8 h-8 rounded-full object-cover\"> <span class=\"text-white text-sm font-medium\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(username)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/dashboard.templ`, Line: 19, Col: 60}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span> <svg class=\"w-4 h-4 text-neutral-500\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"1.7\" d=\"M19 9l-7 7-7-7\"></path></svg></button><div id=\"profile-dropdown\" class=\"absolute right-0 mt-2 w-44 rounded-xl bg-[#0e0e0f] border border-neutral-800 shadow-xl hidden\"><a href=\"/profile/\" class=\"block px-4 py-3 text-sm text-neutral-300 hover:bg-neutral-900\">Profile</a> <a href=\"/logout/\" class=\"block px-4 py-3 text-sm text-red-400 hover:bg-neutral-900\">Logout</a></div></div></div><script>\n    const pb = document.getElementById(\"profile-btn\")\n    const pd = document.getElementById(\"profile-dropdown\")\n    document.addEventListener(\"click\", e => {if (!pb.contains(e.target)) pd.classList.add(\"hidden\")})\n    pb.onclick = () => pd.classList.toggle(\"hidden\")\n  </script><!-- PROJECT SECTION --><div class=\"space-y-4 mb-12\"><h2 class=\"text-neutral-400 font-medium text-sm tracking-wide\">Your Projects</h2><div class=\"overflow-x-auto scrollbar-hide\"><div class=\"flex gap-4 pr-6\"><!-- Loop -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, p := range projects {
			if activeProjectID == p.ID {
				templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, selectProject(p.ID))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<button onclick=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 templ.ComponentScript = selectProject(p.ID)
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3.Call)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" class=\"min-w-[220px] rounded-xl border border-neutral-700 bg-[#0e0e0f] p-4 shadow-md group\"><div class=\"flex items-center justify-between\"><h3 class=\"text-white font-semibold text-base\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(p.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/dashboard.templ`, Line: 52, Col: 64}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</h3><div class=\"flex items-center gap-2\"><svg onclick=\"event.stopPropagation(); syncProject()\" xmlns=\"http://www.w3.org/2000/svg\" class=\"w-4 h-4 text-green-400 opacity-0 group-hover:opacity-100 cursor-pointer hover:scale-110 transition-all\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" title=\"Sync project\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15\"></path></svg><div class=\"h-2 w-2 bg-green-500 rounded-full\"></div></div></div></button>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, selectProject(p.ID))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<button onclick=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 templ.ComponentScript = selectProject(p.ID)
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5.Call)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" class=\"min-w-[220px] rounded-xl border border-neutral-800 bg-[#0e0e0f] p-4\"><div class=\"flex items-center justify-between\"><h3 class=\"text-white font-semibold text-base\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(p.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/dashboard.templ`, Line: 75, Col: 64}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</h3></div></button>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<!-- New project button --><button onclick=\"openProjectModal()\" class=\"min-w-[220px] rounded-xl border border-neutral-800 bg-[#0b0b0c]\n\t\t\t\t\t\tp-4 flex flex-col items-center justify-center text-neutral-500 \n\t\t\t\t\t\thover:text-white hover:border-neutral-600 hover:bg-neutral-900 shadow-md\"><div class=\"h-8 w-8 rounded-full border border-neutral-700 grid place-items-center\"><span class=\"text-xl\">+</span></div><p class=\"mt-2 font-medium text-sm\">New Project</p></button></div></div></div><!-- IF NO ACTIVE PROJECT -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if activeProjectID == "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div class=\"w-full text-center py-20 text-neutral-400 text-lg\">Please select a project to continue.</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<!-- FEATURE SECTIONS --> <div class=\"space-y-4\"><h2 class=\"text-neutral-400 font-medium text-sm tracking-wide\">Tools & Features</h2><div class=\"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6\"><a href=\"/functions/\" class=\"group rounded-2xl border border-neutral-800 bg-[#0e0e0f] p-6 hover:border-neutral-600 shadow-md\"><div class=\"flex items-center gap-3\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"w-6 h-6 text-blue-400\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"1.7\" d=\"M6 18L18 6M6 6l12 12\"></path></svg><h3 class=\"text-lg text-white font-semibold\">Functions</h3></div></a> <a href=\"/endpoints/\" class=\"group rounded-2xl border border-neutral-800 bg-[#0e0e0f] p-6 hover:border-neutral-600 shadow-md\"><div class=\"flex items-center gap-3\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"w-6 h-6 text-purple-400\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"1.7\" d=\"M4 12h16m-7-7l7 7-7 7\"></path></svg><h3 class=\"text-lg text-white font-semibold\">Endpoints</h3></div></a> <a href=\"/configuration/\" class=\"group rounded-2xl border border-neutral-800 bg-[#0e0e0f] p-6 hover:border-neutral-600 shadow-md\"><div class=\"flex items-center gap-3\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"w-6 h-6 text-yellow-400\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"1.7\" d=\"M12 8c-1.1 0-2 .9-2 2v4h4v-4c0-1.1-.9-2-2-2zM4 12h16\"></path></svg><h3 class=\"text-lg text-white font-semibold\">Configuration</h3></div></a></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<!-- MODAL --><div id=\"project-modal\" class=\"fixed inset-0 bg-black bg-opacity-50 hidden justify-center items-center\"><div class=\"bg-[#0e0e0f] border border-neutral-800 rounded-2xl p-6 w-96\"><h3 class=\"text-lg text-white font-semibold\">Create Project</h3><input id=\"new-project-name\" class=\"w-full mt-4 px-3 py-2 bg-[#0b0b0c] border border-neutral-800 rounded-xl text-white\" placeholder=\"Project name\"><div class=\"flex justify-end gap-3 mt-6\"><button onclick=\"closeProjectModal()\" class=\"text-neutral-400\">Cancel</button> <button onclick=\"submitNewProject()\" class=\"bg-white text-black px-4 py-2 rounded-xl font-semibold\">Create</button></div></div></div><script>\n    function openProjectModal() {\n      const modal = document.getElementById(\"project-modal\")\n      modal.classList.remove(\"hidden\")\n      modal.classList.add(\"flex\")\n    }\n    function closeProjectModal() {\n      const modal = document.getElementById(\"project-modal\")\n      modal.classList.add(\"hidden\")\n      modal.classList.remove(\"flex\")\n    }\n\n    async function submitNewProject() {\n      const name = document.getElementById(\"new-project-name\").value.trim()\n      if (!name) return\n      await fetch(\"/api/projects/\", {\n        method: \"POST\",\n        headers: {\"Content-Type\": \"application/json\"},\n        body: JSON.stringify({name})\n      })\n      closeProjectModal()\n      location.reload()\n    }\n\n    async function syncProject() {\n      await fetch(\"/api/projects/sync/\", {\n        method: \"POST\"\n      })\n      alert(\"Sync completed!\")\n      location.reload()\n    }\n  </script></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
