// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package adaptors

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToProject = `-- name: AddUserToProject :exec
INSERT INTO user_projects (user_id, project_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, project_id) DO UPDATE
SET role = EXCLUDED.role
`

type AddUserToProjectParams struct {
	UserID    []byte
	ProjectID pgtype.UUID
	Role      pgtype.Text
}

func (q *Queries) AddUserToProject(ctx context.Context, arg AddUserToProjectParams) error {
	_, err := q.db.Exec(ctx, addUserToProject, arg.UserID, arg.ProjectID, arg.Role)
	return err
}

const createProject = `-- name: CreateProject :one

INSERT INTO projects (name, description, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_by, created_at
`

type CreateProjectParams struct {
	Name        string
	Description pgtype.Text
	CreatedBy   []byte
}

// PROJECT QUERIES
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.Description, arg.CreatedBy)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, created_by, created_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name, description, created_by, created_at
FROM projects
WHERE name = $1
`

func (q *Queries) GetProjectByName(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByName, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT u.id, u.name, u.display_name, u.icon, up.role, up.created_at
FROM user_projects up
JOIN users u ON u.id = up.user_id
WHERE up.project_id = $1
ORDER BY u.name
`

type ListProjectMembersRow struct {
	ID          []byte
	Name        string
	DisplayName string
	Icon        pgtype.Text
	Role        pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Icon,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.name, p.description, p.created_by, p.created_at
FROM projects p
JOIN user_projects up ON up.project_id = p.id
WHERE up.user_id = $1
ORDER BY p.created_at DESC
`

func (q *Queries) ListProjectsForUser(ctx context.Context, userID []byte) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromProject = `-- name: RemoveUserFromProject :exec
DELETE FROM user_projects
WHERE user_id = $1 AND project_id = $2
`

type RemoveUserFromProjectParams struct {
	UserID    []byte
	ProjectID pgtype.UUID
}

func (q *Queries) RemoveUserFromProject(ctx context.Context, arg RemoveUserFromProjectParams) error {
	_, err := q.db.Exec(ctx, removeUserFromProject, arg.UserID, arg.ProjectID)
	return err
}
